apiVersion: v1 

kind: Service 

metadata: 

  name: jupyter-service 

  annotations: 

    service.beta.kubernetes.io/aws-load-balancer-type: alb 

spec: 

  selector: 

    app: jupyter-notebook 

  ports: 

    - protocol: TCP 

      port: 80 

      targetPort: 8888 

  type: LoadBalancer